pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci
      - base=master
    actions:
      merge:
        method: merge
